### ISSUE TITLE
Watermark opacity should be 100%

### ISSUE THREAD

**Issue by tony2guo** [elsa-lab/NTHUthesis#2]
In [博碩士論文上傳說明](https://www.lib.nthu.edu.tw/ETD/downloads/upload.pdf) page 17 and [Thesis/Dissertation Format Reference](https://www.lib.nthu.edu.tw/ETD/downloads/T&Dupload.pdf) page 17 have their watermark opacity set to 100%.
I think the [nthu-logo.pdf](https://github.com/elsa-lab/NTHUthesis/blob/main/nthu-logo.pdf) has already lightened the color, so we may not need to set the opacity. We could revert commit bf45eb1.

But I am not sure about "Scale relative to target page: 50%" in those docs, setting scale=0.5 in draftwatermark makes the watermark too small.

**Comment by KuanYuChang** [comment]
Hi @tony2guo,

Thanks for the feedback. This configuration is decided by "what I think looks better." Note that without reducing its opacity, the watermark may be indistinguishable from the foreground text and thus impede reading. That's why I set it to 0.5. As for the watermark size, do you think it is better to make it larger?

|opacity=1|opacity=0.5|
|---|---|
|![opacity=1](https://user-images.githubusercontent.com/17684437/224549864-e121333e-c9bc-4d91-ba1a-482f0d0d86f9.png)|![opacity= 5](https://user-images.githubusercontent.com/17684437/224549886-20bd118f-503d-4b9b-8645-4e169302c06a.png)|

Regards,
Kuan-Yu

**Comment by KuanYuChang** [comment]
The option "Scale Relative To Target Page" is to resize the watermark in relation to the PDF page dimensions. Thus, I rescale the watermark by setting its width to 50% paper width.

**Comment by tony2guo** [comment]
I agree opacity=0.5 does look better. But since the official document wants opacity=1, I suggest setting opacity=1 as default. Maybe replace the nowatermark option with watermark_opacity, which 0 is no watermark.

**Comment by KuanYuChang** [comment]
Hi @tony2guo,

We gained the app Adobe Acrobat and tried out the setting from 博碩士論文上傳說明 [1]. It turns out that setting the opacity to 100% makes no difference from the document built from LaTeX and will indeed impede reading. However, after an inner struggle, we decided to follow the setting in [1] and left the customization effort to the user who thinks opacity 1 is terrible.

![Screen Shot from Adobe Acrobat](https://user-images.githubusercontent.com/17684437/224793133-4108c75f-582c-490b-85a9-0784239775d6.png)

Sincerely,
Kuan-Yu

Reference
[1] https://www.lib.nthu.edu.tw/ETD/downloads/upload.pdf

**Comment by tony2guo** [comment]
Thanks for the experiment!
